In [1]:
#ARRAY creation and Properties
import numpy as np

In [2]:
m = np.arange(10)
n = np.arange(18)

In [3]:
m
n

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17])

In [4]:
a = np.arange(10).reshape(2,5)

a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [5]:
#NumPy Data
print(a.ndim)
print(a.shape)
print(a.size)
print(a.dtype)
print(a.itemsize)
print(type(a))

2
(2, 5)
10
int32
4
<class 'numpy.ndarray'>


In [6]:
#creating an array from a list
n = np.array( [3.0, 2.0, 6.0, 5.0] )
print(n)
print(n.dtype)
print(type(n))

[3. 2. 6. 5.]
float64
<class 'numpy.ndarray'>


In [7]:
d = np.eye(5)
dtype=np.float32
d

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [8]:
#logspace and linspace
m = np.linspace(-11, 30, 10, endpoint=True)
print(m)

[-11.          -6.44444444  -1.88888889   2.66666667   7.22222222
  11.77777778  16.33333333  20.88888889  25.44444444  30.        ]


In [11]:
r = np.logspace(-11, 30, 10, endpoint=True, base=5)
print(r)

[2.04800000e-08 3.12987245e-05 4.78325270e-02 7.31004435e+01
 1.11716340e+05 1.70731393e+08 2.60921623e+11 3.98755565e+14
 6.09401394e+17 9.31322575e+20]


In [12]:
#initialize an array based on a function
l = np.fromfunction(lambda i, j: i == j, (2, 3), dtype=int)
l

array([[ True, False, False],
       [False,  True, False]])

In [13]:
#Array Operations
m = np.arange(12).reshape(3,4)
print(m)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [14]:
m*4

array([[ 0,  4,  8, 12],
       [16, 20, 24, 28],
       [32, 36, 40, 44]])

In [15]:
m + m

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [16]:
m*m

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [17]:
#transpose
n = n.transpose()
n

array([3., 2., 6., 5.])

In [18]:
m @ n

array([ 29.,  93., 157.])

In [19]:
print(m)
m.sum(axis=1)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


array([ 6, 22, 38])

In [20]:
print(m)
m.sum(axis=0)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


array([12, 15, 18, 21])

In [21]:
m.sum()

66

In [22]:
#Extrema
print(a.min(), a.max())

0 9


In [23]:
#universal functions
n = m*np.pi/10.0
print(n)

[[0.         0.31415927 0.62831853 0.9424778 ]
 [1.25663706 1.57079633 1.88495559 2.19911486]
 [2.51327412 2.82743339 3.14159265 3.45575192]]


In [24]:
l = np.cos(n)
print(l)

[[ 1.00000000e+00  9.51056516e-01  8.09016994e-01  5.87785252e-01]
 [ 3.09016994e-01  6.12323400e-17 -3.09016994e-01 -5.87785252e-01]
 [-8.09016994e-01 -9.51056516e-01 -1.00000000e+00 -9.51056516e-01]]


In [25]:
k = n + l

In [26]:
print(k)

[[1.         1.26521578 1.43733553 1.53026305]
 [1.56565406 1.57079633 1.5759386  1.61132961]
 [1.70425713 1.87637687 2.14159265 2.5046954 ]]


In [27]:
#Array Slicing: Accessing Subarrays
m = np.arange(8)
m

array([0, 1, 2, 3, 4, 5, 6, 7])

In [28]:
m[4]

4

In [29]:
print(m[3:4])

[3]


In [30]:
m[3:4]

array([3])

In [31]:
m[:]

array([0, 1, 2, 3, 4, 5, 6, 7])

In [32]:
#Multidimensional Arrays
m = np.arange(15).reshape(3,5)
m

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [33]:
m[1,2]

7

In [34]:
m[0:1,0:2]

array([[0, 1]])

In [35]:
#specific column
m[:,2]

array([ 2,  7, 12])

In [36]:
m = m.flatten()
print(m)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [37]:
#ITERATE
for h in m:
    print(h)
m = np.arange(15).reshape(3,5)
print(m)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [38]:
for f in m.flat:
    print(f)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14


In [40]:
#Copying Arrays
m = np.arange(10)
print(m)


[0 1 2 3 4 5 6 7 8 9]


In [41]:
n = m
n is m

True

In [42]:
n.shape = (2, 5)
print(n)
m.shape

[[0 1 2 3 4]
 [5 6 7 8 9]]


(2, 5)

In [43]:
n is m

True

In [44]:
print(m)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [45]:
m = np.arange(12)
l = m[:]
m.shape = (3,4)

print(m)
print(l)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [46]:
l[2] = -1
print(m)
print(l)

[[ 0  1 -1  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 0  1 -1  3  4  5  6  7  8  9 10 11]


In [47]:
n = l[4:6]
print(n)

[4 5]


In [48]:
n[:] = 0 

In [49]:
print(m)
print(l)
print(n)

[[ 0  1 -1  3]
 [ 0  0  6  7]
 [ 8  9 10 11]]
[ 0  1 -1  3  0  0  6  7  8  9 10 11]
[0 0]


In [50]:
print(l is m)
print(l.base is m)
print(l.flags.owndata)
print(m.flags.owndata)

False
True
False
True


In [51]:
k = m.copy()
k[:,:] = 1.1

print(m)
print(k)

[[ 0  1 -1  3]
 [ 0  0  6  7]
 [ 8  9 10 11]]
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
