In [1]:
#Boolean indexing
import numpy as np
q = np.arange(12).reshape(2,6)
q

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [2]:
q[q > 7] = 0
q

array([[0, 1, 2, 3, 4, 5],
       [6, 7, 0, 0, 0, 0]])

In [3]:
q[q == 0] = -1
q

array([[-1,  1,  2,  3,  4,  5],
       [ 6,  7, -1, -1, -1, -1]])

In [4]:
q == -1

array([[ True, False, False, False, False, False],
       [False, False,  True,  True,  True,  True]])

In [5]:
#logical and()/or()
q = np.arange(10).reshape(2,5)
q[np.logical_and(q > 4, q <= 8)] = 0.0
q

array([[0, 1, 2, 3, 4],
       [0, 0, 0, 0, 9]])

In [6]:
q > 4

array([[False, False, False, False, False],
       [False, False, False, False,  True]])

In [7]:
#Avoiding Loops
a = 25
b = 40
xmin = ymin = 0.0
xmax = ymax = 1.0

a = np.linspace(xmin, xmax, a, endpoint=False)
b = np.linspace(ymin, ymax, b, endpoint=False)

print(a.shape)
print(b.shape)
a

(25,)
(40,)


array([0.  , 0.04, 0.08, 0.12, 0.16, 0.2 , 0.24, 0.28, 0.32, 0.36, 0.4 ,
       0.44, 0.48, 0.52, 0.56, 0.6 , 0.64, 0.68, 0.72, 0.76, 0.8 , 0.84,
       0.88, 0.92, 0.96])

In [8]:
#Time out Code
import time
import numpy as np
A = 25
B = 40

a = np.linspace(0.0, 1.0, A, endpoint=False)
b = np.linspace(0.0, 1.0, B, endpoint=True)


In [9]:
system = time.time()

p = np.zeros((A, B))
print(p)
for i in range(A):
    for j in range(B):
        p[i,j] = np.sin(2.0*np.pi*a[i]*b[j])       
timetaken = time.time()
print("time elapsed: {} s".format(timetaken-system))

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [10]:
#1-d to 2-d
a2d, b2d = np.meshgrid(a, b, indexing="ij")

print(a2d[:,0])
print(a2d[0,:])

print(b2d[:,0])
print(b2d[0,:])

[0.   0.04 0.08 0.12 0.16 0.2  0.24 0.28 0.32 0.36 0.4  0.44 0.48 0.52
 0.56 0.6  0.64 0.68 0.72 0.76 0.8  0.84 0.88 0.92 0.96]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0.]
[0.         0.02564103 0.05128205 0.07692308 0.1025641  0.12820513
 0.15384615 0.17948718 0.20512821 0.23076923 0.25641026 0.28205128
 0.30769231 0.33333333 0.35897436 0.38461538 0.41025641 0.43589744
 0.46153846 0.48717949 0.51282051 0.53846154 0.56410256 0.58974359
 0.61538462 0.64102564 0.66666667 0.69230769 0.71794872 0.74358974
 0.76923077 0.79487179 0.82051282 0.84615385 0.87179487 0.8974359
 0.92307692 0.94871795 0.97435897 1.        ]


In [11]:
system = time.time()
p1 = np.sin(2.0*np.pi*a2d*b2d)
timetaken = time.time()
print("time elapsed: {} s".format(timetaken-system))

time elapsed: 0.0 s


In [12]:
#Concatenation of arrays
a = np.array([1, 9, 3, 4])
b = np.array([2, 3, 8, 1])
np.concatenate([a,b])

array([1, 9, 3, 4, 2, 3, 8, 1])

In [13]:
n = [0, 0, 0]
print(np.concatenate([n, a, b]))

[0 0 0 1 9 3 4 2 3 8 1]


In [14]:
ddd = np.array([[11, 22, 33],
                 [44, 55, 66]])

In [15]:
np.concatenate([ddd, ddd])

array([[11, 22, 33],
       [44, 55, 66],
       [11, 22, 33],
       [44, 55, 66]])

In [16]:
np.concatenate([ddd, ddd], axis=0)

array([[11, 22, 33],
       [44, 55, 66],
       [11, 22, 33],
       [44, 55, 66]])

In [17]:
#Splitting of arrays
l = [9, 1, 9, 1, 9, 1, 9, 1, 9, 1, 9]
l1, l2, l3,l4 = np.split(l, [2, 0, 1])
print(l1, l2, l3, l4)

[9 1] [] [9] [1 9 1 9 1 9 1 9 1 9]


In [18]:
nayana = np.arange(36).reshape((6, 6))
nayana

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [19]:
left, right = np.vsplit(nayana, [3])
print(left)
print(right)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]]
[[18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]


In [20]:
#Aggregates
man = np.arange(2, 8)
print(man)
np.add.reduce(man)

[2 3 4 5 6 7]


27

In [21]:
np.multiply.reduce(man)

5040

In [22]:
np.add.accumulate(man)

array([ 2,  5,  9, 14, 20, 27], dtype=int32)

In [23]:
np.multiply.accumulate(man)

array([   2,    6,   24,  120,  720, 5040], dtype=int32)